const mongoose = require('mongoose');

const model = mongoose.model("ertu-Settings", mongoose.Schema({
    serverID: { type: String },
    serverTag: { type: String, default: "" },
    secondTag: { type: String, default: "" },
    bannedTags: [String],
    serverURL: { type: String, default: "" },

    public: { type: Boolean, default: true },
    compliment: { type: Boolean, default: true },
    autoRegister: { type: Boolean, default: true },
    taggedMode: { type: Boolean, default: false },
    registerSystem: { type: Boolean, default: true },
    minMinAge: { type: Boolean, default: false },
    autoAuth: { type: Boolean, default: false },
    fastLogin: { type: Boolean, default: false },

    minAge: { type: Number, default: 15 },
    unregisteredLimit: { type: Number, default: 5 },
    muteLimit: { type: Number, default: 5 },
    vmuteLimit: { type: Number, default: 5 },
    jailLimit: { type: Number, default: 5 },
    banLimit: { type: Number, default: 5 },
    etLimit: { type: Number, default: 5 },
    stLimit: { type: Number, default: 5 },

    staffs: [String],
    minStaffs: [String],
    mediumStaffs: [String],
    maxStaffs: [String],
    minAdminRole: { type: String, default: "" },
    minStaffRole: { type: String, default: "" },
    ownerRoles: [String],
    transporterRoles: [String],
    solvingAuth: [String],
    registerAuth: [String],
    jailAuth: [String],
    banAuth: [String],
    voiceMuteAuth: [String],
    chatMuteAuth: [String],
    etAuth: [String],

    manRoles: [String],
    womanRoles: [String],
    unregisterRoles: [String],
    vipRole: { type: String, default: "" },
    familyRole: { type: String, default: "" },
    meetingRole: { type: String, default: "" },
    streamerRole: { type: String, default: "" },

    bannedTagRole: { type: String, default: "" },
    suspectedRole: { type: String, default: "" },
    chatMuteRole: { type: String, default: "" },
    quarantineRole: { type: String, default: "" },
    adsRole: { type: String, default: "" },
    underworldRole: { type: String, default: "" },
    voiceMuteRole: { type: String, default: "" },
    etRole: { type: String, default: "" },
    stRole: { type: String, default: "" },

    streamerResponsible: { type: String, default: "" },
    registerResponsible: { type: String, default: "" },
    authResponsible: { type: String, default: "" },
    returnResponsible: { type: String, default: "" },
    streamerController: { type: String, default: "" },
    registerController: { type: String, default: "" },
    authController: { type: String, default: "" },
    returnController: { type: String, default: "" },
    streamerLeader: { type: String, default: "" },
    authLeader: { type: String, default: "" },
    leaderRoles: [String],

    publicParent: { type: String, default: "" },
    registerParent: { type: String, default: "" },
    streamerParent: { type: String, default: "" },
    solvingParent: { type: String, default: "" },
    activityParent: { type: String, default: "" },
    secretRoomParent: { type: String, default: "" },
    photoChannels: [String],
    chatChannel: { type: String, default: "" },
    afkChannel: { type: String, default: "" },
    registerChannel: { type: String, default: "" },
    inviterChannel: { type: String, default: "" },

    perms: { type: Array, default: [] },
    leaderboard: { type: Object, default: {} },
    staffLeaves: { type: Array, default: [] },
    tagLeaves: { type: Array, default: [] },
}))

module.exports = model;