const mongoose = require('mongoose');

const model = mongoose.model("ertu-User", mongoose.Schema({
  userID: { type: String },
  userName: { type: String },
  UserInviter: { type: String, default: undefined },
  Gender: String,
  Registrant: String,
  Names: { type: Object },
  Records: { type: Object },
  Uses: { type: Object },
  Solvers: { type: Array, default: [] },
  Returns: { type: Array, default: [] },
  Taggeds: { type: Array, default: [] },
  Auths: { type: Array, default: [] },
  PenalPoints: { type: Number, default: 0 },
  Voices: { type: Object, default: {} },
  Messages: { type: Object, default: {} },
  Streams: { type: Object, default: {} },
  Cameras: { type: Object, default: {} },
  LastDayTime: { type: Number, default: () => new Date().setHours(0, 0, 0, 0) },
  Days: { type: Number, default: 1 },
  ChatFriends: { type: Object, default: {} },
  VoiceFriends: { type: Object, default: {} },
  StreamsCount: { type: Number, default: 0 },
  CamerasCount: { type: Number, default: 0 },
  LastMessage: { type: Number, default: 0 },
  LastVoice: { type: Number, default: 0 },
  AfkInformation: { type: Object, default: {} },
  RoleLogs: { type: Array, default: [] },
  VoiceLogs: { type: Array, default: [] },
  Inventory: { type: Object, default: { Cash: 0 } },
  Marriage: { type: Object, default: { active: false, married: undefined, date: undefined, ring: undefined } },
  LeaveInvites: { type: Number, default: 0 },
  NormalInvites: { type: Number, default: 0 },
  Tagged: { type: Boolean, default: false },
}))

module.exports = model;